# general
title: Modern
author: Sergiu Tripon
description: >
    Modern, a Jekyll theme for modern people.
timezone: Europe/London

# urls
url: http://sergiu-tripon.com
baseurl: /modern-on-jekyll

# analytics
google:
  tracking: false
  tracking_id: ""
  site_verification:
bing:
  tracking: false
  site_verification:

# comments
disqus:
  comments: true
  shortname: modern-on-jekyll

# colors
colors:
- '#FF5E3A, #FF2A68, #FFAE9B'
- '#FF9500, #FF5E3A, #FFBF65'
- '#FFDB4C, #FFCD02, #FFE064'
- '#87FC70, #0BD318, #9CFF89'
- '#52EDC7, #5AC8FB, #9BFFE6'
- '#1AD6FD, #1D62F0, #9FEEFF'
- '#C644FC, #5856D6, #E9B5FF'
- '#EF4DB6, #C643FC, #FFB2E4'
- '#5AD427, #A4E786, #B6FF95'
- '#C86EDF, #E4B7F0, #F3C4FF'
- '#FB2B69, #FF5B37, #FFABC4'
- '#1D77EF, #81F3FD, #B0F9FF'
- '#55EFCB, #5BCAFF, #9AFFE7'

# sidebar
sidebar:
  all: true
  search: true
  posts:
    latest: true
    recent: true
  cats_tags: true

# about
about:
  page: true

# archive
archive:
  page: true
  link: /archive/
  cats_link: /archive/categories/
  tags_link: /archive/tags/

# contact
contact:
  page: true

# social
social:
  email:
    address: contact@sergiu-tripon.com
  linkedin:
    share: true
    username: sergiutripon
  github:
    username: SergiuTripon
  behance:
    username: sergiutripon
  stackexchange:
    username: 5167860/sergiu-tripon
  stackoverflow:
    username: 4137308/sergiu-tripon
  paypal:
    username: sergiutripon
  facebook:
    id: 100000005070445
    share: true
    username: triponsergiu
  twitter:
    id: 286066431
    share: true
    locale: en_GB
    username: SergiuTripon
  google_plus:
    share: true
    username: 115463900916675278669
  instagram:
    username: sergiu_tripon
  vine:
    username: 1234534944605372416
  tumblr:
    username: sergiutripon
  skype:
    username: sergiutripon
  soundcloud:
    username: sergiutripon
  spotify:
    username: sergiutripon
  youtube:
    channel: UCSPiq_mmLpXaosA6oG3WNAQ
  vimeo:
    username: sergiutripon

# - http://uk.linkedin.com/in/sergiutripon
# - https://github.com/SergiuTripon
# - http://www.behance.net/SergiuTripon
# - http://stackexchange.com/users/5167860/sergiu-tripon
# - http://stackoverflow.com/users/4137308/sergiu-tripon
# - https://www.paypal.me/sergiutripon
# - http://www.facebook.com/triponsergiu
# - https://twitter.com/SergiuTripon
# - http://plus.google.com/115463900916675278669
# - http://www.instagram.com/sergiu_tripon
# - http://vine.co/u/1234534944605372416
# - http://sergiutripon.tumblr.com
# - skype:sergiutripon?add
# - http://soundcloud.com/sergiutripon
# - http://play.spotify.com/user/sergiutripon
# - http://www.youtube.com/channel/UCSPiq_mmLpXaosA6oG3WNAQ
# - http://vimeo.com/sergiutripon

# defaults
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
      author: Sergiu Tripon
      author-link: /about/
      description: ""
      comments: true
      excerpt_separator: <!--more-->
  -
    scope:
      path: ''
      type: drafts
    values:
      layout: post
      author: Sergiu Tripon
      author-link: /about/
      description: ""
      comments: false
      excerpt_separator: <!--more-->

# build
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  # syntax_highlighter_opts:
    # css_class: 'highlight'
    # span:
      # line_numbers: false
    # block:
      # line_numbers: true
      # start_line: 1
permalink: /:year/:month/:day/:title/
paginate: 5

# exclude
exclude:
- node_modules
- Gruntfile.js
- package.json
- README.md

# gems
gems:
- jekyll-paginate
- jekyll-gist
